version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android-refimpl-app/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
